name: Python autotests
on: 
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options: 
          - smoke
          - regression
          - extendend
          - all
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run autotests
    steps: 
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements
      - name: Run all tests --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'all'"
        continue-on-error: true
        run: pytest
      - name: Run smoke tests --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'smoke'"
        continue-on-error: true
        run: pytest -m smoke
      - name: Run regression tests --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'regression'"
        continue-on-error: true
        run: pytest -m regression
      - name: Run extendend tests --alluredir=allure-results
        if: "github.event.inputs.deployment_target == 'extendend'"
        continue-on-error: true
        run: pytest -m extendend --alluredir=allure-results
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
        
